export const AuditAction = {
  AUTH_LOGIN: 'AUTH_LOGIN',

  COMPANY_CREATED: 'COMPANY_CREATED',
  COMPANY_UPDATED: 'COMPANY_UPDATED',

  USER_CREATED: 'USER_CREATED',
  USER_ROLE_UPDATED: 'USER_ROLE_UPDATED',
  USER_DELETED: 'USER_DELETED',

  WAREHOUSE_CREATED: 'WAREHOUSE_CREATED',
  WAREHOUSE_UPDATED: 'WAREHOUSE_UPDATED',
  WAREHOUSE_DELETED: 'WAREHOUSE_DELETED',

  PRODUCT_CREATED: 'PRODUCT_CREATED',
  PRODUCT_UPDATED: 'PRODUCT_UPDATED',
  PRODUCT_DELETED: 'PRODUCT_DELETED',

  INVENTORY_STOCK_IN: 'INVENTORY_STOCK_IN',
  INVENTORY_STOCK_OUT: 'INVENTORY_STOCK_OUT',
  INVENTORY_ADJUSTED: 'INVENTORY_ADJUSTED',

  REORDER_CREATED: 'REORDER_CREATED',
  REORDER_APPROVED: 'REORDER_APPROVED',
  REORDER_REJECTED: 'REORDER_REJECTED',
} as const;

export type AuditActionType = (typeof AuditAction)[keyof typeof AuditAction];
